expect_that(rmLcPostfix(c('abab','weab')), equals(c('ab','we')))
expect_that(rmLcPostfix(c('qwea','asda','zxca')), equals(c('qwe','asd','zxc')))
expect_that(rmLcPostfix(c('abc','abc')), equals(c('','')))
expect_that(rmLcPostfix(c('abc')), equals(''))
expect_that(rmLcPostfix(''), equals(''))
expect_that(rmLcPostfix(NULL), equals(NULL))
